---
image: node:alpine

# Speed up builds
cache:
  key: $CI_BUILD_REF_NAME # changed to $CI_COMMIT_REF_NAME in Gitlab 9.x
  paths:
    - node_modules

stages:
    - build
    - quality_gate
    - deploy_server

build:
  stage: build
  script:
    - npm ci
    - npm run lint
  except:
    - master
    - merge_requests

sonarcloud-check:
  stage: quality_gate
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master

docker:deploy:
  stage: deploy_server
  image: tiangolo/docker-with-compose
  variables:
    DOCKER_HOST: ''
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml pull
    - docker-compose -f docker-compose.yml up -d
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop"'
      when: on_success
  tags:
    - docker
    - personal
