version: '3.7'

services:
  app:
    image: dolibarr-front-react
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "VIRTUAL_HOST=my.mltech.fr"
      - "LETSENCRYPT_HOST=my.mltech.fr"
      - "NODE_ENV=production"
    networks: 
      - internal
      - nginx-proxy

networks: 
  internal:
  nginx-proxy:
    external: true
