version: '3.7'

services:
  app:
    image: dolibarr-front-react
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      VIRTUAL_HOST: my.mltech.fr
      #LETSENCRYPT_HOST: my.mltech.fr
      NODE_ENV: production
      REACT_APP_SITE_LOGO_URL_MINI: https://dolibarr.mltech.fr/viewimage.php?modulepart=mycompany&file=logos%2Fthumbs%2FLogo_mini.png
      REACT_APP_SITE_LOGO_URL: /dist/img/LogoMLTech.png
      REACT_APP_SITE_NAME: MLTech
      REACT_APP_MAIL_CONTACT: contact@mltech.fr
    networks: 
      - internal
      - nginx-proxy

networks: 
  internal:
  nginx-proxy:
    external: true
