version: '3.4'

services:
  app:
    image: Dolibarr-front-react
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "VIRTUAL_HOST=my.mltech.fr"
      - "LETSENCRYPT_HOST=my.mltech.fr"
      - "NODE_ENV=production"
