version: '3.4'

services:
  espaceclient:
    image: espaceclient
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    environment:
      NODE_ENV: development
      REACT_APP_SITE_LOGO_URL_MINI: http://localhost:8083/viewimage.php?modulepart=mycompany&file=logos%2Fthumbs%2FLogo__ML_mini.png
      REACT_APP_SITE_LOGO_URL: /dist/img/LogoMLTech.png
      REACT_APP_SITE_NAME: MLTech
      REACT_APP_MAIL_CONTACT: contact@mltech.fr
    ports:
      - 3002:3000
