version: '3.7'

services:
  app:
    image: dolibarr-front-react
    restart: always
    ports: 
      - 8085:80
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      VIRTUAL_HOST: my.mltech.fr
      NODE_ENV: production
      REACT_APP_SITE_LOGO_URL_MINI: "/dist/img/LogoMLTech_bg_white.png"
      REACT_APP_SITE_LOGO_URL: /dist/img/LogoMLTech.png
      REACT_APP_SITE_NAME: MLTech
      REACT_APP_MAIL_CONTACT: contact@mltech.fr
      REACT_APP_API_ADDRESS: https://dolibarr.mltech.fr/api/index.php
      REACT_APP_DOLIBARR_INSTANCE: https://dolibarr.mltech.fr/
      REACT_APP_USER_CONTACT: 1
    networks: 
      - internal
      - nginx-proxy

networks: 
  internal:
  nginx-proxy:
    external: true
