version: '3.7'

services:
  app:
    image: dolibarr-front-react
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        REACT_APP_SITE_LOGO_URL_MINI: "https://dolibarr.mltech.fr/viewimage.php?modulepart=mycompany&file=logos%2Fthumbs%2FLogo_mini.png"
        REACT_APP_SITE_LOGO_URL: /dist/img/LogoMLTech.png
        REACT_APP_SITE_NAME: MLTech
        REACT_APP_MAIL_CONTACT: contact@mltech.fr
        REACT_APP_SITE_DESCRIPTION: ${REACT_APP_SITE_DESCRIPTION}
        REACT_APP_API_DEV_ADDRESS: ${REACT_APP_API_DEV_ADDRESS}
        REACT_APP_DOLIBARR_DEV_INSTANCE: ${REACT_APP_DOLIBARR_DEV_INSTANCE}
        REACT_APP_API_PROD_ADDRESS: https://dolibarr.mltech.fr/api/index.php
        REACT_APP_DOLIBARR_PROD_INSTANCE: https://dolibarr.mltech.fr/
        REACT_APP_USER_CONTACT: ${REACT_APP_USER_CONTACT}
    environment:
      VIRTUAL_HOST: my.mltech.fr
      #LETSENCRYPT_HOST: my.mltech.fr
      NODE_ENV: production
    networks: 
      - internal
      - nginx-proxy

networks: 
  internal:
  nginx-proxy:
    external: true
