# build environment
FROM node:alpine as build
WORKDIR /app

RUN echo $REACT_APP_SITE_DESCRIPTION

ARG REACT_APP_SITE_NAME
ARG REACT_APP_SITE_DESCRIPTION
ARG REACT_APP_SITE_LOGO_URL_MINI
ARG REACT_APP_SITE_LOGO_URL
ARG REACT_APP_API_DEV_ADDRESS
ARG REACT_APP_DOLIBARR_DEV_INSTANCE
ARG REACT_APP_API_PROD_ADDRESS
ARG REACT_APP_DOLIBARR_PROD_INSTANCE
ARG REACT_APP_MAIL_CONTACT
ARG REACT_APP_USER_CONTACT

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV=production

ENV REACT_APP_SITE_NAME $REACT_APP_SITE_NAME
ENV REACT_APP_SITE_DESCRIPTION $REACT_APP_SITE_DESCRIPTION
ENV REACT_APP_SITE_LOGO_URL_MINI $REACT_APP_SITE_LOGO_URL_MINI
ENV REACT_APP_SITE_LOGO_URL $REACT_APP_SITE_LOGO_URL
ENV REACT_APP_API_DEV_ADDRESS $REACT_APP_API_DEV_ADDRESS
ENV REACT_APP_DOLIBARR_DEV_INSTANCE $REACT_APP_DOLIBARR_DEV_INSTANCE
ENV REACT_APP_API_PROD_ADDRESS $REACT_APP_API_PROD_ADDRESS
ENV REACT_APP_DOLIBARR_PROD_INSTANCE $REACT_APP_DOLIBARR_PROD_INSTANCE
ENV REACT_APP_MAIL_CONTACT $REACT_APP_MAIL_CONTACT
ENV REACT_APP_USER_CONTACT $REACT_APP_USER_CONTACT

COPY package.json ./
COPY package-lock.json ./
RUN npm i
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
